version: 2
jobs:
   build:
      docker:
         - image: circleci/python:3.6.6-stretch-browsers
      steps:
         - checkout
         - run:
            name: Install python deps
            command: | 
               pip install --user -r requirements.txt
               sudo pip install codecov
               python -m spacy download en
         #- run:
         #   name: run test sample
         #   command: python -m pytest --cov=./ ./test_sample.py
         - run:
            name: run sentiment_RNN_SA for testing
            command: ./test.sh
         #- run:
         #   name: Code coverage
         #   command: codecov