version: 2
jobs:
   build:
      docker:
         - image: circleci/python:3.6.6-stretch-browsers
      steps:
         - checkout
         - run:
            name: Install python deps
            command: pip install --user -r requirements.txt
         - run:
            name: run test sample
            command: python -m pytest --cov=./ ./test_sample.py
         -run:
            name: Code coverage
            command: 