version: 2
jobs:
   build:
      docker:
         - image: circleci/python:3.6.6-stretch-browsers
      steps:
         - checkout
         - run:
            name: Install python deps
            command: pip install -r --user requirements.txt
         - run:
            name: run test sample
            command: pytest test_sample.py